import eslint from "@eslint/js";
import eslintConfigPrettier from "eslint-config-prettier";
import globals from "globals";
import pluginImport from "eslint-plugin-import";
import pluginPrettier from "eslint-plugin-prettier";
import pluginVue from "eslint-plugin-vue";
import tseslint from "typescript-eslint";
import parserVue from "vue-eslint-parser";

export default [
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  ...pluginVue.configs["flat/recommended"],
  eslintConfigPrettier,
  {
    ignores: ["node_modules/", "dist/", "charts/**/*", "docker/", "eslint.config.js"],
    files: ["**/*.js", "**/*.ts", "**/*.vue"],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.node,
      },
      parser: parserVue,
      parserOptions: {
        parser: tseslint.parser,
        sourceType: "module",
        extraFileExtensions: [".vue"],
      },
    },
    plugins: {
      "@typescript-eslint": tseslint.plugin,
      prettier: pluginPrettier,
      vue: pluginVue,
      import: pluginImport,
    },
    settings: {
      "import/resolver": {
        typescript: {
          alwaysTryTypes: true,
          project: "./tsconfig.json",
        },
        alias: {
          map: [
            ["@", "./src"],
            ["Tests", "./tests"],
          ],
          extensions: [".js", ".ts", ".vue", ".scss"],
        },
      },
    },
    rules: {
      "prettier/prettier": [
        "error",
        {
          vueIndentScriptAndStyle: false,
          semi: true,
          singleQuote: false,
          trailingComma: "all",
          printWidth: 120,
          tabWidth: 2,
          useTabs: false,
          bracketSpacing: true,
          arrowParens: "avoid",
          singleAttributePerLine: true,
          bracketSameLine: false,
          htmlWhitespaceSensitivity: "ignore",
          endOfLine: "auto",
        },
      ],
      "import/no-unresolved": "error",
      "import/no-duplicates": "error",
      "import/order": [
        "error",
        {
          groups: ["builtin", "external", "internal"],
          "newlines-between": "always",
        },
      ],
      "no-console": "off",
      "no-debugger": "error",
      eqeqeq: ["error", "always"],
      quotes: ["error", "double", { avoidEscape: true }],
      semi: ["error", "always"],
      "no-shadow": "off",
      "@typescript-eslint/explicit-module-boundary-types": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/consistent-type-definitions": ["error", "interface"],
      "@typescript-eslint/no-empty-function": "error",
      camelcase: "off",
      "@typescript-eslint/naming-convention": [
        "error",
        {
          selector: "variable",
          modifiers: ["exported"],
          format: ["camelCase", "UPPER_CASE", "snake_case", "PascalCase"],
          leadingUnderscore: "allow",
          trailingUnderscore: "allow",
        },
        {
          selector: "variable",
          format: ["camelCase", "UPPER_CASE", "snake_case"],
          leadingUnderscore: "allow",
          trailingUnderscore: "allow",
        },
        {
          selector: "variableLike",
          format: ["camelCase", "UPPER_CASE", "snake_case"],
          leadingUnderscore: "allow",
          trailingUnderscore: "allow",
        },
        {
          selector: "property",
          modifiers: ["requiresQuotes"],
          format: null,
          leadingUnderscore: "allow",
          trailingUnderscore: "allow",
        },
        {
          selector: "property",
          format: ["camelCase", "UPPER_CASE", "snake_case"],
          leadingUnderscore: "allow",
          trailingUnderscore: "allow",
        },
        {
          selector: "parameter",
          format: ["camelCase", "snake_case"],
          leadingUnderscore: "allow",
          trailingUnderscore: "allow",
        },
      ],
      "vue/no-unused-components": "error",
      "vue/no-unused-vars": "error",
      "vue/no-mutating-props": "error",
      "vue/multi-word-component-names": "off",
      "vue/block-order": [
        "error",
        {
          order: ["template", "script", "style"],
        },
      ],
      "vue/max-attributes-per-line": [
        "error",
        {
          singleline: { max: 1 },
          multiline: { max: 1 },
        },
      ],
      "vue/first-attribute-linebreak": [
        "error",
        {
          singleline: "ignore",
          multiline: "below",
        },
      ],
      "vue/html-closing-bracket-newline": ["error", { singleline: "never", multiline: "always" }],
      "vue/html-self-closing": [
        "error",
        {
          html: {
            void: "always",
            normal: "never",
            component: "always",
          },
          svg: "always",
          math: "always",
        },
      ],
      "vue/mustache-interpolation-spacing": ["error", "always"],
      "vue/attribute-hyphenation": ["error", "always"],
      "vue/html-closing-bracket-spacing": [
        "error",
        {
          startTag: "never",
          endTag: "never",
          selfClosingTag: "always",
        },
      ],
      "@typescript-eslint/no-namespace": "off",
      "no-duplicate-imports": ["error", { includeExports: true }],
      "no-template-curly-in-string": "error",
      "block-scoped-var": "error",
      "max-classes-per-file": "off",
      "no-alert": "off",
      "no-else-return": ["error", { allowElseIf: false }],
      "no-implicit-coercion": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-multi-spaces": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-wrappers": "error",
      "no-return-await": "off",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-throw-literal": "error",
      "no-unused-expressions": "off",
      "no-useless-call": "error",
      "no-useless-concat": "error",
      "no-useless-return": "error",
      "prefer-promise-reject-errors": ["error", { allowEmptyReject: true }],
      radix: "error",
      "no-undefined": "off",
      "array-bracket-newline": ["error", { multiline: true }],
      "comma-dangle": ["error", "always-multiline"],
      "comma-style": "error",
      "eol-last": "error",
      "new-parens": "error",
      "no-bitwise": "warn",
      "no-lonely-if": "warn",
      "no-multiple-empty-lines": "error",
      "no-nested-ternary": "error",
      "no-new-object": "error",
      "no-tabs": ["error", { allowIndentationTabs: true }],
      "no-trailing-spaces": "error",
      "no-unneeded-ternary": "error",
      "no-whitespace-before-property": "error",
      "object-curly-newline": "error",
      "spaced-comment": ["error", "always"],
      "switch-colon-spacing": "error",
      "arrow-body-style": ["error", "as-needed"],
      "arrow-parens": ["error", "as-needed"],
      "arrow-spacing": "error",
      "generator-star-spacing": ["error", "after"],
      "no-confusing-arrow": "off",
      "no-useless-computed-key": "error",
      "no-useless-rename": "error",
      "object-shorthand": ["error", "always"],
      "prefer-arrow-callback": "warn",
      "prefer-destructuring": "error",
      "rest-spread-spacing": ["error", "never"],
      "sort-imports": "off",
      "template-curly-spacing": "error",
      "no-prototype-builtins": "off",
      "@typescript-eslint/restrict-template-expressions": "off",
      "@typescript-eslint/restrict-plus-operands": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/adjacent-overload-signatures": "off",
      "@typescript-eslint/member-ordering": "warn",
      "@typescript-eslint/no-magic-numbers": [
        "error",
        {
          ignore: [0, 1, -1],
          ignoreNumericLiteralTypes: true,
          ignoreArrayIndexes: true,
          ignoreEnums: true,
          enforceConst: true,
          ignoreReadonlyClassProperties: true,
        },
      ],
      "brace-style": ["error", "1tbs"],
      "@typescript-eslint/no-useless-constructor": "error",
      "@typescript-eslint/prefer-for-of": "warn",
      "@typescript-eslint/prefer-function-type": "warn",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/explicit-function-return-type": ["error", { allowExpressions: true }],
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_$" }],
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      curly: ["error", "all"],
      "array-bracket-spacing": ["error", "never"],
      "block-spacing": ["error", "always"],
      "comma-spacing": ["error", { before: false, after: true }],
      "computed-property-spacing": ["error", "never"],
      "key-spacing": "error",
      "keyword-spacing": ["error", { before: true, after: true }],
      "object-curly-spacing": ["error", "always"],
      "semi-spacing": ["error", { before: false, after: true }],
      "space-before-blocks": ["error", "always"],
      "space-in-parens": ["error", "never"],
      "space-unary-ops": ["error", { words: true, nonwords: false }],
      "space-before-function-paren": ["error", { anonymous: "always", named: "never", asyncArrow: "always" }],
      "space-infix-ops": "error",
      "vue/no-v-html": "off",
      "vue/no-template-shadow": "off",
      "vue/singleline-html-element-content-newline": "off",
      "@typescript-eslint/no-unused-expressions": "off",
    },
  },
];
