import eslint from "@eslint/js";
import globals from "globals";
import pluginImport from "eslint-plugin-import";
import pluginVue from "eslint-plugin-vue";
import tseslint from "typescript-eslint";
import parserVue from "vue-eslint-parser";
import eslintPluginPrettierRecommended from "eslint-plugin-prettier/recommended";

export default [
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  ...pluginVue.configs["flat/recommended"],
  eslintPluginPrettierRecommended,
  {
    ignores: ["node_modules/", "dist/", "charts/**/*", "docker/", "eslint.config.js"],
    files: ["**/*.js", "**/*.ts", "**/*.vue"],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.node,
      },
      parser: parserVue,
      parserOptions: {
        parser: tseslint.parser,
        sourceType: "module",
        extraFileExtensions: [".vue"],
      },
    },
    plugins: {
      "@typescript-eslint": tseslint.plugin,
      vue: pluginVue,
      import: pluginImport,
    },
    settings: {
      "import/resolver": {
        typescript: {
          alwaysTryTypes: true,
          project: "./tsconfig.json",
        },
        alias: {
          map: [
            ["@", "./src"],
            ["Tests", "./tests"],
          ],
          extensions: [".js", ".ts", ".vue", ".scss"],
        },
      },
    },
    rules: {
      "import/no-unresolved": "error",
      "import/no-duplicates": "error",
      "import/order": [
        "error",
        {
          groups: ["builtin", "external", "internal"],
          "newlines-between": "always",
        },
      ],
      "no-console": "off",
      "no-debugger": "error",
      eqeqeq: ["error", "always"],
      "no-shadow": "off",
      "@typescript-eslint/explicit-module-boundary-types": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/consistent-type-definitions": ["error", "interface"],
      "@typescript-eslint/no-empty-function": "error",
      camelcase: "off",
      "@typescript-eslint/naming-convention": [
        "error",
        {
          selector: "variable",
          modifiers: ["exported"],
          format: ["camelCase", "UPPER_CASE", "snake_case", "PascalCase"],
          leadingUnderscore: "allow",
          trailingUnderscore: "allow",
        },
        {
          selector: "variable",
          format: ["camelCase", "UPPER_CASE", "snake_case"],
          leadingUnderscore: "allow",
          trailingUnderscore: "allow",
        },
        {
          selector: "variableLike",
          format: ["camelCase", "UPPER_CASE", "snake_case"],
          leadingUnderscore: "allow",
          trailingUnderscore: "allow",
        },
        {
          selector: "property",
          modifiers: ["requiresQuotes"],
          format: null,
          leadingUnderscore: "allow",
          trailingUnderscore: "allow",
        },
        {
          selector: "property",
          format: ["camelCase", "UPPER_CASE", "snake_case"],
          leadingUnderscore: "allow",
          trailingUnderscore: "allow",
        },
        {
          selector: "parameter",
          format: ["camelCase", "snake_case"],
          leadingUnderscore: "allow",
          trailingUnderscore: "allow",
        },
      ],
      "vue/no-unused-components": "error",
      "vue/no-unused-vars": "error",
      "vue/no-mutating-props": "error",
      "vue/multi-word-component-names": "off",
      "vue/block-order": [
        "error",
        {
          order: ["template", "script", "style"],
        },
      ],
      "@typescript-eslint/no-namespace": "off",
      "no-duplicate-imports": ["error", { includeExports: true }],
      "no-template-curly-in-string": "error",
      "block-scoped-var": "error",
      "max-classes-per-file": "off",
      "no-alert": "off",
      "no-else-return": ["error", { allowElseIf: false }],
      "no-implicit-coercion": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-wrappers": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-throw-literal": "error",
      "no-useless-call": "error",
      "no-useless-concat": "error",
      "no-useless-return": "error",
      "prefer-promise-reject-errors": ["error", { allowEmptyReject: true }],
      radix: "error",
      "no-undefined": "off",
      "no-bitwise": "warn",
      "no-lonely-if": "warn",
      "no-unneeded-ternary": "error",
      "arrow-body-style": ["error", "as-needed"],
      "no-useless-computed-key": "error",
      "no-useless-rename": "error",
      "object-shorthand": ["error", "always"],
      "prefer-arrow-callback": "warn",
      "prefer-destructuring": "error",
      "sort-imports": "off",
      "no-prototype-builtins": "off",
      "@typescript-eslint/restrict-template-expressions": "off",
      "@typescript-eslint/restrict-plus-operands": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/adjacent-overload-signatures": "off",
      "@typescript-eslint/member-ordering": "warn",
      "@typescript-eslint/no-magic-numbers": [
        "error",
        {
          ignore: [0, 1, -1],
          ignoreNumericLiteralTypes: true,
          ignoreArrayIndexes: true,
          ignoreEnums: true,
          enforceConst: true,
          ignoreReadonlyClassProperties: true,
        },
      ],
      "@typescript-eslint/no-useless-constructor": "error",
      "@typescript-eslint/prefer-for-of": "warn",
      "@typescript-eslint/prefer-function-type": "warn",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/explicit-function-return-type": ["error", { allowExpressions: true }],
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_$" }],
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      curly: ["error", "all"],
      "vue/no-v-html": "off",
    },
  },
];
